project:
  type: website

website:
  title: "FAS1002_projet-finsession"
  description: | 
    "Page d'accueil du travail final pour le cours FAS1002 -
    Initiation à la programmation en sciences sociales à
    l'Université de Montréal donné lors du trimestre A2022."

  reader-mode: true
# URL de votre site une fois publié - <VOTREUSERNAME> à changer 
  site-url: https://amelie-lr.github.io/FAS1002_projet-finsession/
# URL de votre répertoire - VOTREUSERNAME/VOTRE-RÉPERTOIRE à changer
  repo-url: https://github.com/amelie-lr/FAS1002_projet-finsession
  repo-actions: [edit, issue, source]
  
# Options à changer pour le menu ou la barre de navigation
  navbar:
    background: dark
    logo: /assets/img/FAS1002.png 	# Logo image to be displayed left of the title.
    logo-alt: Logo du cours FAS1002
    # Alternate text for the logo image.
    search: true
    # menu
    left:
      - href: index.qmd
        text: Accueil
      - href: intro.qmd
        text: Introduction
      - href: import.qmd
        text: Importation
      - href: exploration.qmd
        text: Exploration
    right:
      - href: a-propos.qmd
        text: FAS1002 

# footer
  page-footer:
    left: |
      [Propulsé par des logiciels libres 💖](https://github.com/FAS1002/A22){.nav-link}
    center:
    # Changer VOTRE NOM pour ce que vous voulez
      - text: "Amélie LR"
        href: mailto:amelie.levasseur-raymond@umontreal.ca
    right:
      - icon: github
        href: https://github.com/FAS1002/
        aria-label: GitHub du cours FAS1002
        

# set favicon
  favicon: /assets/img/FAS1002.png
format:
  html:
    theme: [solar, assets/scss/styles-solar.scss]
#      light: [flatly, assets/scss/styles.css]
#      dark: [darkly, assets/scss/styles-dark.scss]
    code-fold: true
    code-copy: true
    code-overflow: wrap
    highlight-style: github
    toc: true
    lang: "fr"
    smooth-scroll: true

execute:
  freeze: auto
  
editor: source
